version: '3.8'

services:
  app:
    build: ./
    container_name: rabbitmq-task1-c1
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db
  db:
    image: mysql:8.4.0
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
